module.exports = {
  'Quercus robur': {
    commonNames: ['Chêne pédonculé', 'Chêne commun'],
    characteristics: {
      Écorce: 'Fissurée, gris brunâtre, épaisse chez les sujets âgés.',
      Feuilles: 'Larges, lobées, 7 à 9 lobes arrondis.',
      Fleurs: 'Chatons mâles pendants au printemps.',
      Hauteur: '30 à 40 m en pleine maturité.',
      Habitat: 'Forêts feuillues, haies, zones calcaires et terrains humides.',
    },
    uses: 'Bois durable pour la menuiserie, la charpente et la tonnellerie.',
    conservationStatus: 'Préoccupation mineure',
  },
  'Pinus sylvestris': {
    commonNames: ['Pin sylvestre', 'Pin rouge'],
    characteristics: {
      Écorce: 'Ecailleuse, orangée sur les sujets jeunes, gris brun chez les vieux sujets.',
      Feuilles: 'Aiguilles longues de 4 à 7 cm par paires.',
      Cônes: 'Oeufs à ovés, 3 à 7 cm.',
      Hauteur: '20 à 35 m.',
      Habitat: 'Sols pauvres, landes, forêts boréales et montagneuses.',
    },
    uses: 'Bois de construction, pâte à papier, résine et reforestation.',
    conservationStatus: 'Préoccupation mineure',
  },
  'Betula pendula': {
    commonNames: ['Bouleau blanc', 'Bouleau verruqueux'],
    characteristics: {
      Écorce: 'Blanche, mince, se desquame en lambeaux.',
      Feuilles: 'Triangulaires, dentées, 3 à 7 cm.',
      Fleurs: 'Amentes pédonculés pendants.',
      Hauteur: '15 à 25 m.',
      Habitat: 'Zones humides, friches, bords de rivières.',
    },
    uses: 'Bois léger, papier, médicinal (sève, écorce).',
    conservationStatus: 'Préoccupation mineure',
  },
  'Fagus sylvatica': {
    commonNames: ['Hêtre', 'Hêtre commun'],
    characteristics: {
      Écorce: 'Lisse, gris argenté, même sur les vieux arbres.',
      Feuilles: 'Ova les à ovales, bordées de dents arrondies.',
      Fleurs: 'Mâles en grappes, femelles solitaires.',
      Hauteur: '30 à 35 m.',
      Habitat: 'Forêts fraîches, sols profonds et humides.',
    },
    uses: 'Bois de chauffage, menuiserie, parquets et mobiliers.',
    conservationStatus: 'Préoccupation mineure',
  },
  'Abies alba': {
    commonNames: ['Sapin blanc', 'Sapin des Alpes'],
    characteristics: {
      Écorce: 'Lisse, grise, avec des résines collantes chez les jeunes sujets.',
      Feuilles: 'Aiguilles plates de 2 à 3 cm, brillantes.',
      Cônes: 'Dressés, cylindriques, 10 à 20 cm.',
      Hauteur: '35 à 50 m.',
      Habitat: 'Forêts de montagne, sols acides et frais.',
    },
    uses: 'Bois d’oeuvre, sapin de Noël, production de pâte à papier.',
    conservationStatus: 'Préoccupation mineure',
  },
  'Acer pseudoplatanus': {
    commonNames: ['Érable sycomore', 'Érable faux-platane'],
    characteristics: {
      Écorce: 'Fissurée, grise et parfois rugueuse.',
      Feuilles: 'Palmées à 5 lobes, 10 à 18 cm.',
      Fleurs: 'Jaunâtres, en grappes au printemps.',
      Hauteur: '20 à 35 m.',
      Habitat: 'Boisements, bords de route, parcs urbains.',
    },
    uses: 'Bois dur pour ébénisterie, placages et meubles.',
    conservationStatus: 'Préoccupation mineure',
  },
  'Ulmus procera': {
    commonNames: ['Orme champêtre', 'Orme anglais'],
    characteristics: {
      Écorce: 'Fissurée, gris foncé avec des crevasses longitudinales.',
      Feuilles: 'Asymétriques, dentées, 7 à 12 cm.',
      Fleurs: 'Petites, groupées avant les feuilles.',
      Hauteur: '20 à 30 m.',
      Habitat: 'Haies, bordures de champs, sols frais.',
    },
    uses: 'Bois souple et résistant pour charpente, mobilier et écluses.',
    conservationStatus: 'Quasi menacé',
  },
  'Populus tremuloides': {
    commonNames: ['Tremble', 'Peuplier faux-tremble'],
    characteristics: {
      Écorce: 'Lisse, blanchâtre à vert pâle, souvent marquée de tâches sombres.',
      Feuilles: 'Triangulaires, ondulées, avec nervures très visibles.',
      Fleurs: 'Amentes pendants au printemps.',
      Hauteur: '15 à 25 m.',
      Habitat: 'Rives, clairières, sols frais et humides.',
    },
    uses: 'Bois léger pour pâte, bois de mine, ameublement.',
    conservationStatus: 'Préoccupation mineure',
  },
  'Tilia platyphyllos': {
    commonNames: ['Tilleul à grandes feuilles', 'Tilleul d’Europe'],
    characteristics: {
      Écorce: 'Grise, fissurée verticalement chez les vieux sujets.',
      Feuilles: 'Grandes, cordées, dentées.',
      Fleurs: 'Jaunâtres, très parfumées en grappes.',
      Hauteur: '20 à 30 m.',
      Habitat: 'Bois frais, vallées, parcs et allées urbaines.',
    },
    uses: 'Bois tendre pour sculpture, médico-mélisse et apiculture.',
    conservationStatus: 'Préoccupation mineure',
  },
  'Larix decidua': {
    commonNames: ['Mélèze d’Europe', 'Mélèze'],
    characteristics: {
      Écorce: 'Ecailleuse, brun rougeâtre.',
      Feuilles: 'Aiguilles groupées en bouquets de 30 à 40.',
      Cônes: 'Petits, 2 à 3 cm, dressés.',
      Hauteur: '20 à 40 m.',
      Habitat: 'Montagnes, sols bien drainés, clairières. ',
    },
    uses: 'Bois imputrescible pour charpente, poteaux et mobilier extérieur.',
    conservationStatus: 'Préoccupation mineure',
  },
};
